spring:
  profiles:
    active: local #default
---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379


---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: myredis
      port: 6379